Update appstore_apps.yml

diff --git a/.github/workflows/appstore_apps.yml b/.github/workflows/appstore_apps.yml
--- a/.github/workflows/appstore_apps.yml
+++ b/.github/workflows/appstore_apps.yml
@@ -1,8 +1,9 @@
 name: Latest iOS Apps from App Store
+
 on:
   workflow_dispatch:
   schedule:
-    - cron: '0 0 */2 * *'  # Runs every two days
+    - cron: '0 0 */2 * *' # Runs every two days
 
 permissions:
   contents: write
@@ -13,15 +14,31 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-
       - name: Fetch iOS apps from App Store
         run: |
-          APP_LIST=$(curl -s "https://itunes.apple.com/lookup?id=238f082f-d67c-4d12-b2ed-0d528b84837d&entity=software" | jq -r '.results[] | "- [" + .trackName + "](" + .trackViewUrl + ")"')
+          # Replace 'YOUR_DEVELOPER_ID' with your actual developer ID (numeric)
+          DEVELOPER_ID="2c2e7702-5ffb-4978-a4d4-44ff12678df0"
+          APP_LIST=$(curl -s "https://itunes.apple.com/lookup?id=${DEVELOPER_ID}&entity=software")
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch data from iTunes API"
+            exit 1
+          fi
+          
+          FORMATTED_LIST=$(echo "$APP_LIST" | jq -r '.results[] | "- [" + .trackName + "](" + .trackViewUrl + ")\n"')
+          if [ -z "$FORMATTED_LIST" ]; then
+            echo "No apps found or empty response"
+            exit 1
+          fi
           
           # Insert app list into README.md where the placeholder is
-          sed -i '/<!-- APP-STORE-LIST-START -->/,/<!-- APP-STORE-LIST-END -->/c\\n<!-- APP-STORE-LIST-START -->\n'"${APP_LIST}"'\n<!-- APP-STORE-LIST-END -->' README.md
-
+          sed -i '/<!-- APP-STORE-LIST-START -->/,/<!-- APP-STORE-LIST-END -->/c\
+          <!-- APP-STORE-LIST-START -->\n'"${FORMATTED_LIST}"'<!-- APP-STORE-LIST-END -->' README.md
+      - name: Check for changes
+        id: git-check
+        run: |
+          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT
       - name: Commit changes
+        if: steps.git-check.outputs.changes == 'true'
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
